# Generated by Django 3.0.7 on 2020-06-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
    ]
