# Generated by Django 3.0.7 on 2020-06-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='username',
        ),
    ]
