# Generated by Django 3.0.7 on 2020-06-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_accountuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='working_hour',
            field=models.DecimalField(decimal_places=1, default=8, max_digits=24),
        ),
    ]
